---
yamtrack_version: latest
yamtrack_redis_version: 8-alpine
yamtrack_port: 8001
yamtrack_external_port: 10010
enabled_services:
  - yamtrack-redis-container.service
  - yamtrack-container.service
  - caddy.service
