---
project_name: actual
actual_port: 5006
actual_external_port: 10002
actual_external_url: "https://{{ tailscale_domain }}:{{ actual_external_port }}"
# renovate: datasource=docker depName=docker.io/actualbudget/actual-server
actual_version: "latest@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3"
enabled_services:
  - actual-container.service
  - caddy.service
