---
project_name: actual
actual_port: 5006
actual_external_port: 10002
actual_external_url: "https://{{ tailscale_domain }}:{{ actual_external_port }}"
# renovate: datasource=docker depName=docker.io/actualbudget/actual-server
actual_version: "latest@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5"
enabled_services:
  - actual-container.service
  - caddy.service
