---
project_name: authelia
# renovate: datasource=docker depName=docker.io/authelia/authelia
authelia_version: "4.39.26@sha256:16b804fbf6704b456ffb6e474c8e9d2406f9544ca0fecfeca7b4dcbed647deb4"
authelia_port: 9091
authelia_external_port: 10010
authelia_external_url: "https://{{ tailscale_domain }}:{{ authelia_external_port }}"
authelia_db_host: "{{ postgres_host }}"
authelia_db_name: authelia
authelia_db_user: authelia
authelia_ldap_address: "ldap://lldap:3890"
authelia_ldap_base_dn: dc=frontend,dc=internal
authelia_ldap_user: uid=search,ou=people,dc=frontend,dc=internal
enabled_services:
  - authelia-container.service
  - caddy.service
