---
project_name: authelia
# renovate: datasource=docker depName=docker.io/authelia/authelia
authelia_version: "4.39.24@sha256:8f428b06bb07bb978c10477527634f19ef3b049c9c87321fda14e24d8fc4c535"
authelia_port: 9091
authelia_external_port: 10010
authelia_external_url: "https://{{ tailscale_domain }}:{{ authelia_external_port }}"
authelia_db_host: "{{ postgres_host }}"
authelia_db_name: authelia
authelia_db_user: authelia
authelia_ldap_address: "ldap://lldap:3890"
authelia_ldap_base_dn: dc=frontend,dc=internal
authelia_ldap_user: uid=search,ou=people,dc=frontend,dc=internal
enabled_services:
  - authelia-container.service
  - caddy.service
