---
project_name: authelia
# renovate: datasource=docker depName=docker.io/authelia/authelia
authelia_version: "4.39.27@sha256:ea6ddce051110a0459b9393117a86383771269aac72f89cabe07f3e9e07f892d"
authelia_port: 9091
authelia_external_port: 10010
authelia_external_url: "https://{{ tailscale_domain }}:{{ authelia_external_port }}"
authelia_db_host: "{{ postgres_host }}"
authelia_db_name: authelia
authelia_db_user: authelia
authelia_ldap_address: "ldap://lldap:3890"
authelia_ldap_base_dn: dc=frontend,dc=internal
authelia_ldap_user: uid=search,ou=people,dc=frontend,dc=internal
enabled_services:
  - authelia-container.service
  - caddy.service
