---
- name: Create a Quadlet file
  become: true
  no_log: true
  containers.podman.podman_container:
    name: miniflux
    image: docker.io/miniflux/miniflux:{{ miniflux_version }}
    state: quadlet
    quadlet_filename: "{{ project_name }}-container"
    network: "{{ default_podman_interface }}"
    ports:
      - 127.0.0.1:{{ miniflux_port }}:8080
    env:
      TZ: "{{ timezone }}"
      LISTEN_ADDR: 0.0.0.0:8080
      BASE_URL: "{{ miniflux_external_url }}"
      DATABASE_URL: "postgres://{{ miniflux_db_user }}:{{ miniflux_db_password }}@{{ miniflux_db_host }}:5432/{{ miniflux_db_name }}?sslmode=disable"
      RUN_MIGRATIONS: "1"
      CREATE_ADMIN: "1"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: "{{ miniflux_admin_password }}"
      DISABLE_LOCAL_AUTH: "true"
      OAUTH2_PROVIDER: oidc
      OAUTH2_OIDC_PROVIDER_NAME: Authelia
      OAUTH2_OIDC_DISCOVERY_ENDPOINT: "{{ authelia_external_url }}"
      OAUTH2_CLIENT_ID: miniflux
      OAUTH2_CLIENT_SECRET: "{{ miniflux_oauth2_client_secret }}"
      OAUTH2_REDIRECT_URL: "{{ miniflux_external_url }}/oauth2/oidc/callback"
    labels:
      managed-by: ansible
      part-of: "{{ project_name }}"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for miniflux
    - Restart miniflux
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/etc/caddy/conf.d/{{ project_name }}.Caddyfile"
    group: caddy
    mode: "0644"
    owner: caddy
  notify:
    - Reload systemd for miniflux
    - Restart miniflux
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
