---
- name: Set up arch box
  hosts: all
  roles:
    - system
    - role: disks
      when: "'vm' not in group_names and 'pi' not in group_names"
    - editor
    - mounts
    - backups
    - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'production' in group_names"
      tags: tailscale
    - notifications
    - file_manager
    - reverse_proxy
    - drift_management
    - role: dashboard_server
      tags: homer
    - role: budget_server
      tags: actual
    - role: recipe_server
      tags: mealie
    - role: feed_server
      tags: freshrss
    - role: photo_server
      tags: immich
    - role: bookmark_server
      tags: karakeep
    - role: document_server
      tags: paperless
    - role: nt_file_server
      tags: samba
      become: true
    - role: version_control_server
      tags: forgejo
    - role: home_automation_server
      tags: homeassistant
    - role: directory_server
      tags: lldap
