---
- name: Set up arch box
  hosts: all
  roles:
    - system
    - editor
    - backups
    - firewall
    - containers
    - terminal
    - artis3n.tailscale.machine
    - notifications
    - file_manager
    - mounts
    - reverse_proxy
    - role: dashboard_server
      tags: homer
    - role: file_sync_server
      tags: syncthing
    - role: budget_server
      tags: actual
    - role: recipe_server
      tags: mealie
    - role: feed_server
      tags: freshrss
    - role: photo_server
      tags: immich
    - role: bookmark_server
      tags: karakeep
    - role: document_server
      tags: paperless
    - role: version_control_server
      tags: forgejo
