---
- name: Set up arch box
  hosts: all
  roles:
    - system
    - editor
    - backups
    - firewall
    - containers
    - terminal
    - artis3n.tailscale.machine
    - notifications
    - file_manager
    - mounts
    - reverse_proxy
