---
- name: Restart tailscaled
  become: true
  ansible.builtin.service:
    name: tailscaled.service
    state: restarted
- name: Restart caddy
  become: true
  ansible.builtin.service:
    name: caddy.service
    state: restarted
