---
- name: Create config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/homeassistant"
    state: directory
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: homeassistant
    image: lscr.io/linuxserver/homeassistant:{{ homeassistant_version }}
    state: quadlet
    quadlet_filename: homeassistant-container
    network: host
    env:
      PUID: 1000
      PGID: 1000
      TZ: "{{ timezone }}"
    volumes:
      - "{{ podman_data_dir }}/homeassistant:/config:rw,z"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for homeassistant
    - Restart homeassistant
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/conf.d/homeassistant.Caddyfile
    group: caddy
    mode: "0644"
    owner: caddy
  notify:
    - Reload systemd for homeassistant
    - Restart homeassistant
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Allow Home Assistant (IoT)
  become: true
  community.general.ufw:
    rule: allow
    src: "{{ iot_network }}"
    port: "8123"
    proto: tcp
    comment: Home Assistant/IoT Network
- name: Allow Home Assistant (guest)
  become: true
  community.general.ufw:
    rule: allow
    src: "{{ guest_network }}"
    port: "8123"
    proto: tcp
    comment: Home Assistant/Guest Network
- name: Copy borgmatic config
  become: true
  ignore_errors: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/homeassistant.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
