---
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "/etc/caddy/conf.d/{{ project_name }}.Caddyfile"
    group: caddy
    mode: "0644"
    owner: caddy
  notify:
    - Restart caddy
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
