---
project_name: memos
memos_port: 5230
memos_external_port: 10012
memos_external_url: "https://{{ tailscale_domain }}:{{ memos_external_port }}"
# renovate: datasource=docker depName=docker.io/neosmemo/memos
memos_version: "0.30.0@sha256:71a5b4738d1bed96e92112004054f0888e92791b64eb78afd79077c96e6f9327"
memos_db_host: "{{ postgres_host }}"
memos_db_name: memos
memos_db_user: memos
enabled_services:
  - memos-container.service
  - caddy.service
