---
project_name: memos
memos_port: 5230
memos_external_port: 10012
memos_external_url: "https://{{ tailscale_domain }}:{{ memos_external_port }}"
# renovate: datasource=docker depName=docker.io/neosmemo/memos
memos_version: "0.31.0@sha256:24c2707ddd8fbd2ceaa7a61ecab86a53cdcde640b24ce572b73da14b00b5785f"
memos_db_host: "{{ postgres_host }}"
memos_db_name: memos
memos_db_user: memos
enabled_services:
  - memos-container.service
  - caddy.service
