---
project_name: karakeep
karakeep_port: 3000
karakeep_external_port: 10006
karakeep_external_url: "https://{{ tailscale_domain }}:{{ karakeep_external_port }}"
# renovate: datasource=docker depName=docker.io/getmeili/meilisearch
karakeep_meilisearch_version: "v1.53.2@sha256:c94e58ca09662dd6e65e8f1b0fd145767be3da7d5422a863a27b8d2b68e090c9"
# renovate: datasource=docker depName=ghcr.io/karakeep-app/karakeep
karakeep_server_version: "0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c"
# renovate: datasource=docker depName=ghcr.io/karakeep-app/karakeep-chrome
karakeep_chrome_version: "151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7"
service_data_dir: "{{ podman_nfs_data_dir }}/karakeep-assets"
enabled_services:
  - karakeep-server-container.service
  - karakeep-chrome-container.service
  - karakeep-meilisearch-container.service
  - caddy.service
