---
project_name: karakeep
karakeep_port: 3000
karakeep_external_port: 10006
karakeep_external_url: "https://{{ tailscale_domain }}:{{ karakeep_external_port }}"
# renovate: datasource=docker depName=docker.io/getmeili/meilisearch
karakeep_meilisearch_version: "v1.52.0@sha256:d36e713e8f89483af1ab0d72011bbd503f5ab100b68ccbfad51c39e3f0a0567d"
# renovate: datasource=docker depName=ghcr.io/karakeep-app/karakeep
karakeep_server_version: "0.33.1@sha256:5467873df817ab3aa837f2b06bd7f2b0974132ba1ae5bce0b7e2fd134abc269b"
# renovate: datasource=docker depName=gcr.io/zenika-hub/alpine-chrome
karakeep_chrome_version: "124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f"
service_data_dir: "{{ podman_nfs_data_dir }}/karakeep-assets"
enabled_services:
  - karakeep-server-container.service
  - karakeep-chrome-container.service
  - karakeep-meilisearch-container.service
  - caddy.service
