---
project_name: postgres
# renovate: datasource=docker depName=docker.io/postgres
postgres_version: "18@sha256:7157393f508fd8eb46119937fab39813783fe3e7d4c6316c45c12ce2ea25e61d"
enabled_services:
  - postgres-container.service
