---
tailscale_authkey: "dummy"
username: alex
group: alex
podman_data_dir: "/var/opt"
default_quadlet_options:
  - AutoUpdate=registry
  - Pull=missing
  - |
    [Unit]
    After=network-online.target nss-lookup.target autofs.service

    [Service]
    Restart=always

    [Install]
    WantedBy=default.target
default_podman_interface: "podman1"
timezone: "America/New_York"
dropbear_authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDwZLPWMML0VW/Uw/iVoDriAJ0XF7LupuZ7AhPa5aaTG alex@laptop-pro"
