---
project_name: open-webui
openwebui_port: 18080
openwebui_external_port: 10013
openwebui_external_url: "https://{{ tailscale_domain }}:{{ openwebui_external_port }}"
# renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
openwebui_version: "v0.10.2@sha256:9fcea9c6e32ab60b0498f3986c6cdf651ddbe61db48d2213a3d28048ddd673d4"
openwebui_db_host: "{{ postgres_host }}"
openwebui_db_name: openwebui
openwebui_db_user: openwebui
enabled_services:
  - open-webui-container.service
  - caddy.service
