---
domain_name: frontend.internal
unas_uid: 977
unas_gid: 988
unas2_domain: "unas2.internal"
lan_borg_repo: "{{ unas2_domain }}:/var/nfs/shared/borg"
autofs_mounts:
  - name: immich-upload
    fstype: nfs
    remote: "nas.internal:/srv/nfs/immich-upload"
    options: nfsvers=4,rw,hard,noatime,nodiratime
  - name: immich-encoded-video
    fstype: nfs
    remote: "nas.internal:/srv/nfs/immich-encoded-video"
    options: nfsvers=4,rw,hard,noatime,nodiratime
  - name: karakeep-assets
    fstype: nfs
    remote: "nas.internal:/srv/nfs/karakeep-assets"
    options: nfsvers=4,rw,hard,noatime,nodiratime
  - name: paperless-consume
    fstype: nfs
    remote: "nas.internal:/srv/samba/paperless-consume"
    options: nfsvers=4,rw,hard,noatime,nodiratime
# TODO: Organize this better
authelia_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_db_password') }}"
authelia_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_jwt_secret') }}"
authelia_session_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_session_secret') }}"
authelia_storage_encryption_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_storage_encryption_key') }}"
authelia_oidc_hmac_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_oidc_hmac_secret') }}"
authelia_oidc_jwks_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/authelia_oidc_jwks_key', returnall=true) }}"
memos_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/memos_db_password') }}"
memos_oidc_client_secret_hash: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/memos_oidc_client_secret_hash') }}"
borg_passphrase: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/borg_passphrase') }}"
forgejo_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_db_password') }}"
forgejo_internal_token: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_internal_token') }}"
forgejo_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_jwt_secret') }}"
forgejo_lfs_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_lfs_jwt_secret') }}"
forgejo_oidc_client_secret_hash: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_oidc_client_secret_hash') }}"
guest_network: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/guest_network') }}"
immich_database_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/immich_database_password') }}"
immich_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/immich_smb_password') }}"
karakeep_meili_master_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_meili_master_key') }}"
karakeep_nextauth_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_nextauth_secret') }}"
karakeep_openai_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_openai_key') }}"
karakeep_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_smb_password') }}"
lldap_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_db_password') }}"
lldap_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_jwt_secret') }}"
lldap_key_seed: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_key_seed') }}"
lldap_search_user_pass: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_search_user_pass') }}"
lldap_user_pass: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_user_pass') }}"
paperless_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/paperless_db_password') }}"
paperless_secret_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/paperless_secret_key') }}"
postgres_host: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/postgres_host') }}"
paperless_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/paperless_smb_password') }}"
pushover_application_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/pushover_application_key') }}"
remote_borg_repo_path: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/remote_borg_repo_path') }}"
tailscale_domain: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/tailscale_domain') }}"
yamtrack_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_secret') }}"
yamtrack_trakt_api_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_trakt_api_secret') }}"
yamtrack_trakt_api: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_trakt_api') }}"
postgres_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/postgres_password') }}"
