---
domain_name: frontend.internal
unas_uid: 977
unas_gid: 988
unas2_domain: "unas2.internal"
lan_borg_repo: "{{ unas2_domain }}:/var/nfs/shared/borg"
autofs_mounts:
  - name: shared
    fstype: nfs
    remote: "nas.internal:/srv/nfs/shared"
    options: nfsvers=4,rw,hard,noatime,nodiratime
samba_shares:
  - name: paperless_consume
    comment: Paperless consume
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: epson
    write_list: epson
    user: "{{ username }}"
  - name: ludusavi
    comment: Game save backups
    owner: "{{ username }}"
    group: "{{ group }}"
    directory_mode: "0755"
    valid_users: gamepc
    write_list: gamepc
    user: "{{ username }}"
samba_users:
  - name: epson
    password: "{{ epson_smb_password }}"
  - name: gamepc
    password: "{{ gamepc_smb_password }}"
# TODO: Organize this better
borg_passphrase: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/borg_passphrase') }}"
epson_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/epson_smb_password') }}"
forgejo_db_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_db_password') }}"
forgejo_internal_token: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_internal_token') }}"
forgejo_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_jwt_secret') }}"
forgejo_lfs_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/forgejo_lfs_jwt_secret') }}"
gamepc_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/gamepc_smb_password') }}"
guest_network: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/guest_network') }}"
immich_database_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/immich_database_password') }}"
immich_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/immich_smb_password') }}"
karakeep_meili_master_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_meili_master_key') }}"
karakeep_nextauth_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_nextauth_secret') }}"
karakeep_openai_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_openai_key') }}"
karakeep_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/karakeep_smb_password') }}"
lldap_jwt_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_jwt_secret') }}"
lldap_key_seed: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_key_seed') }}"
lldap_user_pass: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/lldap_user_pass') }}"
mealie_openai_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/mealie_openai_key') }}"
paperless_secret_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/paperless_secret_key') }}"
postgres_host: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/postgres_host') }}"
paperless_smb_password: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/paperless_smb_password') }}"
pushover_application_key: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/pushover_application_key') }}"
remote_borg_repo_path: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/remote_borg_repo_path') }}"
tailscale_domain: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/tailscale_domain') }}"
yamtrack_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_secret') }}"
yamtrack_trakt_api_secret: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_trakt_api_secret') }}"
yamtrack_trakt_api: "{{ lookup('community.general.passwordstore', 'Repositories/frontend-infra/yamtrack_trakt_api') }}"
