---
project_name: forgejo
# renovate: datasource=docker depName=codeberg.org/forgejo/forgejo
forgejo_version: "16@sha256:a3e33d03e771d3e58b27de5573c3a25dc4f670583a6724c1878a6d0bbecf3556"
forgejo_port: 13000
forgejo_external_port: 10008
forgejo_external_url: "https://{{ tailscale_domain }}:{{ forgejo_external_port }}"
forgejo_ssh_port: 222
forgejo_db_host: "{{ postgres_host }}"
forgejo_db_name: gitea
forgejo_db_user: gitea
service_data_dir: "{{ podman_nfs_data_dir }}/forgejo-git"
enabled_services:
  - forgejo-container.service
  - caddy.service
