---
project_name: forgejo
# renovate: datasource=docker depName=codeberg.org/forgejo/forgejo
forgejo_version: "15@sha256:9e14382433760127c87cb78c4dbc44b45abbb0c09c8479812c8e99b3dc893429"
forgejo_port: 13000
forgejo_external_port: 10008
forgejo_external_url: "https://{{ tailscale_domain }}:{{ forgejo_external_port }}"
forgejo_ssh_port: 222
forgejo_db_host: "{{ postgres_host }}"
forgejo_db_name: gitea
forgejo_db_user: gitea
enabled_services:
  - forgejo-container.service
  - caddy.service
