---
project_name: forgejo
# renovate: datasource=docker depName=codeberg.org/forgejo/forgejo
forgejo_version: "16@sha256:2fdfe28b5c68f82f49580e227b84e2afb43af0250e0631a54a386ef3b1d9b759"
forgejo_port: 13000
forgejo_external_port: 10008
forgejo_external_url: "https://{{ tailscale_domain }}:{{ forgejo_external_port }}"
forgejo_ssh_port: 222
forgejo_db_host: "{{ postgres_host }}"
forgejo_db_name: gitea
forgejo_db_user: gitea
service_data_dir: "{{ podman_nfs_data_dir }}/forgejo-git"
enabled_services:
  - forgejo-container.service
  - caddy.service
