---
packages:
  - nfs-utils
  - cifs-utils
aur_packages:
  - name: autofs
    commit: 306f421ed6f3abaaa1c7d4b4b765362e3ac9fb47
enabled_services:
  - autofs
autofs_mounts: []
nfs_idmap_domain: internal
