---
project_name: homeassistant
homeassistant_port: 8123
homeassistant_external_port: 10009
# renovate: datasource=docker depName=lscr.io/linuxserver/homeassistant
homeassistant_version: "2026.7.1@sha256:e443d191ba181dbcd3e0549b595a59c107a01cfe2c3581413aa62a75e304b96c"
enabled_services:
  - homeassistant-container.service
  - caddy.service
