---
project_name: homeassistant
homeassistant_port: 8123
homeassistant_external_port: 10009
# renovate: datasource=docker depName=lscr.io/linuxserver/homeassistant
homeassistant_version: "2026.6.4@sha256:6c2d67dee510d8bb159f371a39215d6a83d6bd77f479a50309212253cfe141a2"
enabled_services:
  - homeassistant-container.service
  - caddy.service
