---
project_name: paperless
# renovate: datasource=docker depName=docker.io/library/redis
paperless_redis_version: "8@sha256:0a972391db0b24ec336e35d1bc98b237237e26f82bf5120cf2f6b1688d1df973"
# renovate: datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
paperless_server_version: "2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f"
# renovate: datasource=docker depName=docker.io/gotenberg/gotenberg
paperless_gotenberg_version: "8.25@sha256:f9104080d9a7ecab253fb5ebe75100329cf5699c33ec0448f2ea02d885dfde4b"
# renovate: datasource=docker depName=docker.io/apache/tika
paperless_tika_version: "latest@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973"
paperless_port: 8000
paperless_external_port: 10007
paperless_db_host: "{{ postgres_host }}"
paperless_db_name: paperless
paperless_db_user: paperless
enabled_services:
  - paperless-redis-container.service
  - paperless-gotenberg-container.service
  - paperless-tika-container.service
  - paperless-server-container.service
  - caddy.service
