---
project_name: immich
immich_redis_version: "9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9"
immich_postgres_version: "14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23"
immich_server_version: "v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5"
immich_ml_version: "v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3"
immich_port: 2283
immich_external_port: 10005
service_data_dir: "{{ podman_nfs_data_dir }}/immich-upload {{ podman_nfs_data_dir }}/immich-encoded-video"
enabled_services:
  - immich-redis-container.service
  - immich-machine-learning-container.service
  - immich-postgres-container.service
  - immich-server-container.service
  - caddy.service
