---
project_name: immich
# renovate: datasource=docker depName=docker.io/valkey/valkey
immich_redis_version: "9@sha256:c123e3715db63d06d4ad6964884037aa0d5d4d703939b9929954112889708e1d"
# manually managed
immich_postgres_version: "14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23"
# renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
immich_server_version: "v3.2.2@sha256:79cc1623323d5894922686d8743b4780181428f98eecbfb58ce12c41ef02d1ea"
# renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
immich_ml_version: "v3.2.2@sha256:60dfcf266a9ef3b7376f5678e8c980d4fb61db5fc48c078fe8a326ab1535d60d"
immich_port: 2283
immich_external_port: 10005
immich_external_url: "https://{{ tailscale_domain }}:{{ immich_external_port }}"
service_data_dir: >-
  {{ podman_nfs_data_dir }}/immich-upload
  {{ podman_nfs_data_dir }}/immich-encoded-video
  {{ podman_nfs_data_dir }}/immich-thumbs
  {{ podman_nfs_data_dir }}/immich-backups
enabled_services:
  - immich-redis-container.service
  - immich-machine-learning-container.service
  - immich-postgres-container.service
  - immich-server-container.service
  - caddy.service
