---
project_name: miniflux
miniflux_port: 11080
miniflux_external_port: 10004
miniflux_external_url: "https://{{ tailscale_domain }}:{{ miniflux_external_port }}"
# renovate: datasource=docker depName=docker.io/miniflux/miniflux
miniflux_version: "2.3.2@sha256:cd353a6af9ce663291f405eddef26fa0d567f486b521c5d34e3fb50e41938b9a"
miniflux_db_host: "{{ postgres_host }}"
miniflux_db_name: miniflux
miniflux_db_user: miniflux
enabled_services:
  - miniflux-container.service
  - caddy.service
